### ISSUE TITLE
Please add official CERT Polska Blocklist

### ISSUE THREAD

**Issue by hg1978** [AdguardTeam/HostlistsRegistry#176] opened 2023-02-26 17:11 UTC
### Prerequisites

- [X] The blocklist is created specifically for DNS-level blockers;
- [X] The blocklist is regularly updated (at least 10 updates per month);
- [X] The blocklist is known and popular;
- [X] The blocklist satisfies [the repo requirements](https://github.com/AdguardTeam/HostlistsRegistry#-what-blocklists-can-be-added-here);

### Blocklist name

List of malicious domains CERT Polska

### Blocklist category

Malware&phishing blocking

### Homepage

https://hole.cert.pl/domains/domains.txt

### Explanation

It’s an official CERT list of malicious domains.

**Comment by Sergey-Lyapin** [comment] 2023-03-07 13:34
`The blocklist should have a place for receiving user complaints and holding discussions, such as a repository on github.com, or a public website/forum.
`
Is there such a place? I didn't find it.

**Comment by Sergey-Lyapin** [comment] 2023-03-07 13:36
duplicate of https://github.com/AdguardTeam/HostlistsRegistry/issues/91

**Closed by Sergey-Lyapin** 2023-03-07 13:36 UTC
Labels: duplicate, blocklist
