### ISSUE TITLE
Add French blocklist to DNS AdGuard

### ISSUE THREAD

**Issue by computman007** [AdguardTeam/HostlistsRegistry#55] opened 2022-06-14 20:30 UTC
I propose to add FR (France) blocklist to AdGuard DNS

https://filters.adtidy.org/extension/ublock/filters/16.txt
or
https://easylist-downloads.adblockplus.org/liste_fr.txt

Don't know which one is better if a choice must be made

**Comment by krystian3w** [comment] 2022-06-15 12:05
AdGuard file have almost all rules from Liste FR - see https://github.com/AdguardTeam/FiltersRegistry/blob/master/filters/ThirdParty/filter_113_ListeFR/diff.txt to detect disabled rules compatible with HOSTS (IP aren't).


Also maybe duplicate of #16

**Comment by ameshkov** [comment] 2022-12-06 07:53
Duplicate of #16 indeed

**Closed by ameshkov** 2022-12-06 07:53 UTC
Labels: duplicate
