### ISSUE TITLE
adguard dns beta Blocklist Suggestion

### ISSUE THREAD

**Issue by 88Va2wFDcYd1CT** [AdguardTeam/HostlistsRegistry#21] opened 2022-03-30 08:54 UTC
List-KR DNS
List-KR(https://github.com/List-KR/List-KR)
is a web filter for websites in Korean language. with AdGuard ad blocker and uBlock Origin.
List-KR DNS filter is Optimized for dns filtering.

https://github.com/List-KR/List-KR/raw/master/filter_DNS.txt

It would be nice if this list could be used in adguard dns beta.

**Comment by ameshkov** [comment] 2022-04-04 06:55
Duplicate of #11. Please upvote the original issue instead.

**Closed by ameshkov** 2022-04-04 06:55 UTC
